version: '3.2'

services:
  postgres:
      image: postgres:latest
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
      - "5432:5432"
  redis:
      image: redis
      ports:
      - "6379:6379"


  aiohttp_blog:
    build: .
    volumes:
      - ./:/app
    command: ./run_service.sh
    ports:
      - "8080:8080"
    depends_on:
      - postgres
